spring: #???? ??
  datasource: #???? 2?
    url: jdbc:mysql://34.64.185.37:3306/mydb
    username: root
    password: impati
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate: #???? 4?
      ddl-auto: create
    properties: #???? 4?
      hibernate: #???? 6?
        format_sql: true
        default_batch_fetch_size: 1000
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

  #logging.level:
#  org.hibernate.SQL: debug


file:
  dir: /root/home/myboot/images/

server:
  port: 8080
## org.hibernate.type: trace


#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