spring: #???? ??
  datasource: #???? 2?
    url: jdbc:h2:tcp://localhost/~/vessel #4?
    username: vessel
    password: vessel
    driver-class-name: org.h2.Driver
  jpa:
    hibernate: #???? 4?
      ddl-auto: create
    properties: #???? 4?
      hibernate: #???? 6?
        format_sql: true
        default_batch_fetch_size: 1000
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

  #logging.level:
#  org.hibernate.SQL: debug


file:
  dir: /Users/jun-yeongchoe/Desktop/project/myFileStore/

server:
  port: 8080
## org.hibernate.type: trace


#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