spring: #???? ??
  datasource: #???? 2?
    url: jdbc:h2:tcp://localhost/~/vessel #4?
    username: vessel
    password: vessel
    driver-class-name: org.h2.Driver
  jpa:
    hibernate: #???? 4?
      ddl-auto: create
    properties: #???? 4?
      hibernate: #???? 6?
        format_sql: true
        default_batch_fetch_size: 1000

#logging.level:
#  org.hibernate.SQL: debug

server:
  port: 8080
## org.hibernate.type: trace


